[project]
name = "defi-sentinel-contracts"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.token-sale-v5]
path = "contracts/token-sale-v5.clar"
epoch = "3.1"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
